{% set version = "0.18" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qtlcharts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qtlcharts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qtlcharts/qtlcharts_{{ version }}.tar.gz
  sha256: af095fc68478994eb7f0f5ad06ef0d65a4baba9753265d796a392940b25334a8

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmlwidgets
    - r-qtl >=1.30_4
  run:
    - r-base
    - r-htmlwidgets
    - r-qtl >=1.30_4

test:
  commands:
    - $R -e "library('qtlcharts')"           # [not win]
    - "\"%R%\" -e \"library('qtlcharts')\""  # [win]

about:
  home: https://kbroman.org/qtlcharts, https://github.com/kbroman/qtlcharts
  license: GPL-3.0-only
  summary: Web-based interactive charts (using D3.js) for the analysis of experimental crosses to identify genetic loci (quantitative trait loci, QTL) contributing to variation in quantitative traits.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: qtlcharts
# Version: 0.11-6
# Date: 2019-02-04
# Title: Interactive Graphics for QTL Experiments
# Author: Karl W Broman [aut, cre], Michael Bostock [ctb, cph] (d3.js library in htmlwidgets/lib, https://d3js.org), Justin Palmer [ctb, cph] (d3.tip library in htmlwidgets/lib, https://github.com/caged/d3-tip), Cynthia Brewer [cph] (ColorBrewer library in htmlwidgets/lib, http://colorbrewer2.org), Mark Harrower [cph] (ColorBrewer library in htmlwidgets/lib, http://colorbrewer2.org), The Pennsylvania State University [cph] (ColorBrewer library in htmlwidgets/lib, http://colorbrewer2.org), jQuery Foundation [cph] (jQuery library in htmlwidgets/lib, https://jquery.com), jQuery contributors [ctb] (jQuery library in htmlwidgets/lib; see https://github.com/jquery/jquery/blob/master/AUTHORS.txt), jQuery UI contributors [ctb] (jQuery UI library in htmlwidgets/lib; see https://jqueryui.com/about)
# Maintainer: Karl W Broman <broman@wisc.edu>
# Description: Web-based interactive charts (using D3.js) for the analysis of experimental crosses to identify genetic loci (quantitative trait loci, QTL) contributing to variation in quantitative traits.
# Depends: R (>= 2.15)
# Imports: qtl (>= 1.30-4), htmlwidgets, graphics, stats, utils
# Suggests: htmltools, jsonlite, knitr, devtools, roxygen2, rmarkdown, testthat
# License: GPL-3 | file LICENSE
# URL: https://kbroman.org/qtlcharts, https://github.com/kbroman/qtlcharts
# BugReports: https://github.com/kbroman/qtlcharts/issues
# LazyData: true
# Encoding: UTF-8
# ByteCompile: true
# RoxygenNote: 6.1.1
# Authors@R: c( person("Karl W", "Broman", role=c("aut", "cre"), email="broman@wisc.edu"), person("Michael", "Bostock", role=c("ctb", "cph"), comment="d3.js library in htmlwidgets/lib, https://d3js.org"), person("Justin", "Palmer", role=c("ctb", "cph"), comment="d3.tip library in htmlwidgets/lib, https://github.com/caged/d3-tip"), person("Cynthia", "Brewer", role="cph", comment="ColorBrewer library in htmlwidgets/lib, http://colorbrewer2.org"), person("Mark", "Harrower", role="cph", comment="ColorBrewer library in htmlwidgets/lib, http://colorbrewer2.org"), person("The Pennsylvania State University", role="cph", comment="ColorBrewer library in htmlwidgets/lib, http://colorbrewer2.org"), person("jQuery Foundation", role="cph", comment="jQuery library in htmlwidgets/lib, https://jquery.com"), person("jQuery contributors", role = "ctb", comment = "jQuery library in htmlwidgets/lib; see https://github.com/jquery/jquery/blob/master/AUTHORS.txt"), person("jQuery UI contributors", role = "ctb", comment = "jQuery UI library in htmlwidgets/lib; see https://jqueryui.com/about"))
# NeedsCompilation: no
# Packaged: 2019-02-05 15:05:42 UTC; kbroman
# Repository: CRAN
# Date/Publication: 2019-02-05 16:20:03 UTC
