appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: O7WamugISPc5bhNx7oiOlbI/rLoUvjliuvs8bDXa5s/oHWpYFFz9nWk1Su7wNNbGnI+WfJB9u7WF+Miv2yKrzTLFHd/ZLGLFRiowwXWjVMRnjtARSgySmWvp6gVbGlPqGmFoQ62uCh6BiLvfT3+pw+MbS43lNrelHyAvmbiUkqFGnADbk3CXGkFLnJiooIY8JVvccZdZyQnS3Pxc3EkKf7Zzbe2ANsfr2ft5R3QaW/hGbxGEHOkAEBninQGZqq5JW5bxn74JjxGRoZBckdnn8t4SBS+JIIp7i3hQ0mPyPULF7WW2QqqFhsYRVqOutFgr0iXCqB3z+wFMJ9qxw1UXRvWGQIN815vN57rpUPIbZm4ZoYLiSAiC0AXgB8Fyjw+B34R9i8ZQJnNDE2C81mVGkd/+zm8FjzXolNfz3kG4U9Kd102uoJYo6hdoVHB9HSdxpWJ3s+oY3Ycu82IKIuw9ga21lsmiK+vF6oywCdEYo73z43E0nZ7x9QeLW/E20Q3OqqrzQvXvmTQn2nzqqRwXBPl6qwoSSRqdVSpg+CP17e8KeF0j9ZprmxZlj7gu60wVvT9FCyVEelPaqB/UIJsYjdw25Sfcfehl3r5RGHRmtIocWB1Sa7C6wlup7MIpF36nHxLO5JREeD4LSX+Mpm37X/colUMaLO3Z+/ZEXHJn5pU=}
bot:
  automerge: true
